### ISSUE TITLE
安装不了吗

### ISSUE THREAD

**Issue by wuhu201314** [evan-gyy/nonebot_plugin_sd_webui#1]
这是反馈ERROR: Could not find a version that satisfies the requirement nonebot-plugin-sd-webui (from versions: none)
ERROR: No matching distribution found for nonebot-plugin-sd-webui

**Comment by evan-gyy** [comment]
可能因为设置过清华源等镜像站，而这个包还没从pypi同步过去，你可以先指定从pypi安装：
```
pip install nonebot-plugin-sd-webui -i https://www.pypi.org/simple/
```
过两天镜像站应该就会同步

**Comment by wuhu201314** [comment]
ok
